# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
set_msg_config -id {Common 17-41} -limit 10000000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/Projects/NanoProcessor/NanoProcessor.cache/wt [current_project]
set_property parent.project_path D:/Projects/NanoProcessor/NanoProcessor.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:basys3:part0:1.2 [current_project]
set_property ip_output_repo d:/Projects/NanoProcessor/NanoProcessor.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  D:/Projects/NanoProcessor/NanoProcessor.srcs/sources_1/new/ALU.vhd
  D:/Projects/NanoProcessor/NanoProcessor.srcs/sources_1/new/ALU_Mux.vhd
  D:/Projects/NanoProcessor/NanoProcessor.srcs/sources_1/new/Add_Sub_Reg_Trf.vhd
  D:/Projects/NanoProcessor/NanoProcessor.srcs/sources_1/new/Add_Sub_Reg_Trf_CU.vhd
  D:/Projects/NanoProcessor/NanoProcessor.srcs/sources_1/new/Add_Subtract.vhd
  D:/Projects/NanoProcessor/NanoProcessor.srcs/sources_1/new/Adder_3.vhd
  D:/Projects/NanoProcessor/NanoProcessor.srcs/sources_1/new/Adder_4Bit.vhd
  D:/Projects/NanoProcessor/NanoProcessor.srcs/sources_1/new/Bit_comparetor.vhd
  D:/Projects/NanoProcessor/NanoProcessor.srcs/sources_1/new/Bit_logical_Comparetor.vhd
  D:/Projects/NanoProcessor/NanoProcessor.srcs/sources_1/new/Buff_3.vhd
  D:/Projects/NanoProcessor/NanoProcessor.srcs/sources_1/new/Buff_4.vhd
  D:/Projects/NanoProcessor/NanoProcessor.srcs/sources_1/new/Comparetor.vhd
  D:/Projects/NanoProcessor/NanoProcessor.srcs/sources_1/new/Count_3.vhd
  D:/Projects/NanoProcessor/NanoProcessor.srcs/sources_1/new/D_FF.vhd
  D:/Projects/NanoProcessor/NanoProcessor.srcs/sources_1/new/Decoder_2_to_4.vhd
  D:/Projects/NanoProcessor/NanoProcessor.srcs/sources_1/new/Decoder_3_to_8.vhd
  D:/Projects/NanoProcessor/NanoProcessor.srcs/sources_1/new/FA.vhd
  D:/Projects/NanoProcessor/NanoProcessor.srcs/sources_1/new/HA.vhd
  D:/Projects/NanoProcessor/NanoProcessor.srcs/sources_1/new/Ins_Decoder.vhd
  D:/Projects/NanoProcessor/NanoProcessor.srcs/sources_1/new/LUT_7_Display.vhd
  D:/Projects/NanoProcessor/NanoProcessor.srcs/sources_1/new/Logical_Comparetor.vhd
  D:/Projects/NanoProcessor/NanoProcessor.srcs/sources_1/new/Multiplicator.vhd
  D:/Projects/NanoProcessor/NanoProcessor.srcs/sources_1/new/Mux_2_way_3.vhd
  D:/Projects/NanoProcessor/NanoProcessor.srcs/sources_1/new/Mux_2_way_4.vhd
  D:/Projects/NanoProcessor/NanoProcessor.srcs/sources_1/new/Mux_8_way_4.vhd
  D:/Projects/NanoProcessor/NanoProcessor.srcs/sources_1/new/ROM_8.vhd
  D:/Projects/NanoProcessor/NanoProcessor.srcs/sources_1/new/Reg.vhd
  D:/Projects/NanoProcessor/NanoProcessor.srcs/sources_1/new/Reg_Bank.vhd
  D:/Projects/NanoProcessor/NanoProcessor.srcs/sources_1/new/Slow_Clk.vhd
  D:/Projects/NanoProcessor/NanoProcessor.srcs/sources_1/new/Processor.vhd
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/Projects/NanoProcessor/NanoProcessor.srcs/constrs_1/imports/new/Basys3Labs.xdc
set_property used_in_implementation false [get_files D:/Projects/NanoProcessor/NanoProcessor.srcs/constrs_1/imports/new/Basys3Labs.xdc]

set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top Processor -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Processor.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Processor_utilization_synth.rpt -pb Processor_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
