@echo off
REM ****************************************************************************
REM Vivado (TM) v2018.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Thu Jun 08 21:24:48 +0530 2023
REM SW Build 2258646 on Thu Jun 14 20:03:12 MDT 2018
REM
REM Copyright 1986-2018 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
call xsim Shift_operator_Sim_behav -key {Behavioral:sim_1:Functional:Shift_operator_Sim} -tclbatch Shift_operator_Sim.tcl -view C:/Users/Tharusha/Documents/Academic Semester 02/Computer Organization and Digital Designing/Nano Processor Challenge/nano processor/NanoProcessor/Processor_Sim_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
